-- ============================================================
-- E-commerce Customer & Business Analytics Platform
-- Load cleaned CSV files into PostgreSQL
--
-- Run from the project root:
-- psql ecommerce_analytics -f database/load_data.sql
-- ============================================================

\set ON_ERROR_STOP on

BEGIN;

-- Clear existing data so this script can be rerun safely.
TRUNCATE TABLE
    ecommerce.reviews,
    ecommerce.payments,
    ecommerce.order_items,
    ecommerce.orders,
    ecommerce.customers,
    ecommerce.products,
    ecommerce.sellers,
    ecommerce.geolocation,
    ecommerce.category_translation
RESTART IDENTITY CASCADE;

-- ============================================================
-- 1. Customers
-- ============================================================

\copy ecommerce.customers (customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state) FROM 'data/processed/customers_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 2. Products
-- ============================================================

\copy ecommerce.products (product_id, product_category_name, product_name_length, product_description_length, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm, missing_product_category_flag, missing_weight_flag, missing_dimensions_flag, weight_outlier_flag, length_outlier_flag, height_outlier_flag, width_outlier_flag, product_volume_cm3, heavy_product_flag) FROM 'data/processed/products_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 3. Sellers
-- ============================================================

\copy ecommerce.sellers (seller_id, seller_zip_code_prefix, seller_city, seller_state) FROM 'data/processed/sellers_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 4. Orders
-- ============================================================

\copy ecommerce.orders (order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, missing_approval_date_flag, missing_carrier_date_flag, missing_delivery_date_flag, purchase_date, purchase_year, purchase_month, purchase_quarter, purchase_year_month, purchase_day_name, purchase_hour, approval_hours, delivery_days, estimated_delivery_days, delivery_difference_days, late_delivery) FROM 'data/processed/orders_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 5. Order Items
-- ============================================================

\copy ecommerce.order_items (order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, price_outlier_flag, freight_outlier_flag, item_total_value, freight_percentage) FROM 'data/processed/order_items_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 6. Payments
-- ============================================================

\copy ecommerce.payments (order_id, payment_sequential, payment_type, payment_installments, payment_value, payment_outlier_flag, multiple_installments, high_value_payment) FROM 'data/processed/payments_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 7. Reviews
-- review_row_id is generated by PostgreSQL.
-- ============================================================

\copy ecommerce.reviews (review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp, missing_review_title_flag, missing_review_message_flag, positive_review, negative_review) FROM 'data/processed/reviews_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 8. Geolocation
-- geolocation_row_id is generated by PostgreSQL.
-- ============================================================

\copy ecommerce.geolocation (geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state) FROM 'data/processed/geolocation_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

-- ============================================================
-- 9. Category Translation
-- ============================================================

\copy ecommerce.category_translation (product_category_name, product_category_name_english) FROM 'data/processed/category_translation_clean.csv' WITH (FORMAT CSV, HEADER TRUE, NULL '', ENCODING 'UTF8');

COMMIT;

\echo 'All cleaned CSV files loaded successfully.'